/**
 * @file servok.c
 *
 * @brief      Servo controller implementation. Uses manual pwm generated by systick and implements two system call for enabling and disabling servos. 
 *
 * @date       
 *
 * @author Nick Toldalagi, Kunal Barde
 */

#include <unistd.h>
#include <syscall.h>
#include <gpio.h>
#include <servok.h>
#include <debug.h>
#define UNUSED __attribute__((unused))

/**
  Minimum period of servo pwm pulses in ms. Corresponds to 0 deg. 
*/
#define SERVO_MIN_WIDTH 0.6

/** Counter of interrupt ticks associated with servo0. Depends on current angle. Updated with servo set. */
uint32_t servo0_tick_num = 0;

/** Counter of interrupt ticks associated with servo1. Depends on current angle. Updated with servo set. */
uint32_t servo1_tick_num = 0; 

/** binary value of whether servo0 is enabled. Changed by servo enable calls.*/
uint8_t servo0_en = 0;
/** binary value of whether servo1s is enabled. Changed by servo enable calls.*/
uint8_t servo1_en = 0;

/**
* @brief	Implementation of system call for servo enable. 

* @param	channel	Servo channel to enable (1 or 0). 
* @param	enabled	Flag to indicated whether to enable to disable the servo. Servo will be disabled if enabled == 0 and enabled otherwise. 

* @return	0 on success, -1 on failure (most likely for requesting an incorrect channel).
*/
int sys_servo_enable(UNUSED uint8_t channel, UNUSED uint8_t enabled){
  if(channel > 1) return -1;
  gpio_port port = (channel == 0) ? GPIO_B : GPIO_A;
  uint32_t pin_num = (channel == 0) ? SERVO0_PIN : SERVO1_PIN;
  if(enabled) {
    if(channel == 0) servo0_en = 1;
    else servo1_en = 1;
    gpio_init(port, pin_num, MODE_GP_OUTPUT, OUTPUT_PUSH_PULL, OUTPUT_SPEED_LOW, PUPD_NONE, ALT0);
  } else {
    gpio_clr(port, pin_num);
    if (channel == 0) {
      servo0_tick_num = 0;
      servo0_en = 0;
    } else {
      servo1_tick_num = 0;
      servo1_en = 0;
    }
  } 
  return 0;
}

/**
* @brief	Implementation of system call for servo set. 

* @param	channel	Servo channel to set (1 or 0).
* @param	angle	Angle to set the channel to.

* @return	0 on success, -1 on failure if the servo channel is not enabled. 
*/
int sys_servo_set(UNUSED uint8_t channel, UNUSED uint8_t angle){
  if(channel == 0) {
    if(!servo0_en) return -1;
    servo0_tick_num = (uint32_t)(((float)angle/100.0 + SERVO_MIN_WIDTH)/.01);
  } else if(channel == 1) {
    if(!servo1_en) return -1;
    servo1_tick_num = (uint32_t)(((float)angle/100.0 + SERVO_MIN_WIDTH)/.01);
  } else {
    return -1;
  }
  return 0;
}
